var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                xxxx                            ",
   "                                              xx!!!!xx                          ",
   "                                             x!!!!!!!!x                         ",
   "                                            xx!!    !!xx                        ",
   "                                                oooo                    xxxx    ",
   "                                                                           x    ",
   "                                                                    oo     x    ",
   "  xxx                                                            xxxxxxxxxxx    ",
   "  x                         ooo                                  x              ",
   "  x                        xxxxxx                                x              ",
   "  x @          o           x    x   xxx           yy             x              ",
   "  xxxxxxxx             o   x    x              xxxxx         oo yx              ",
   "         x                 x    x        o             xxxxxxxxxxx              ",
   "         x            yy   x    x       xxx            x                        ",
   "         x           xxxx  x    x!!!!!!!!!!!!!!!!!!!!!!x                        ",
   "         x!!!!!!!!!!!x  x  x    x!!!!!!!!!!!!!!!!!!!!!!x                        ",
   "         xxxxxxxxxxxxx  x!!x    xxxxxxxxxxxxxxxxxxxxxxxx                        ",
   "                        x!!x                                                    ",
   "                        xxxx                                                    ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
   ["                                                                                ",
    "        xxxxxx                                                                        ",
    "       x!     x                              o                         x              ",
    "      x!       x                             o                      oo x          ",
    "     x!         o                          xxx                o  xxxxxxxx                    ",
    "      x!     @  o                               !!!           xxx                        ",
    "         o xxxx                        y                   xx                    ",
    "              !                      xxx                                          ",
    "              !                                  xx                         ",
    "              !                               oy    oo                          ",
    "              xxxxx                           xx    xxy                                  ",
    "              xxx!!!!!                         x                           ",
    "                     x            y                                                  ",
    "   xyyyy             xxxxx    xxxxx                                                         ",
    "                         x!!!!x     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                                ",
    "                         x!!!!x     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                                 ",
    "                                                                               ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    " !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                                                         ",
    " !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                                                               ",
    "                                                                                ",
    "                                                                                "]

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
